export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Education } from "./Education";
export { default as Experience } from "./Experience";
export { default as Footer } from "./Footer";
export { default as GoogleAnalytics } from "./GoogleAnalytics";
export { default as Hero } from "./Hero";
export { default as HomePage } from "./HomePage";
export { default as Navbar } from "./Navbar";
export { default as Projects } from "./Projects";
export { default as Skills } from "./Skills";
export { StructuredData, generateArticleSchema } from "./StructuredData";
export { default as ThemeProvider } from "./ThemeProvider";
export { default as ThemeToggle } from "./ThemeToggle";
